# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  eslint:
    docker:
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - run:
          name: "Lint the code with Eslint"
          command: |
            npm i
            npm run eslint
  jest_unit_test:
    docker:
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - run:
          name: "Perform unit test with Jest"
          command: |
            pwd
            ls

workflows:
  version: 2
  linting_and_unit_test:
    jobs:
      - eslint
      - jest_unit_test